@Ticketing.Command_HostAddress = http://localhost:5001

GET {{ Ticketing.Command_HostAddress }}/weatherforecast/
Accept: application/json

###

POST {{ Ticketing.Command_HostAddress }}/api/ticket
Accept: application/json
Content-Type: application/json

{
    "username": "JuanPerez",
    "typeError": "ErrorSystem",
    "detailError": "la tienda estaba cerrada"
}
